version: '3.8'
services:
  preprod-webfluxblog-blog-service: # The name of the service
    container_name: preprod-webfluxblog-blog-service  # Setting the container name
    image: preprod-webfluxblog-blog-service-local-image
    restart: always # Always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087" # Map The current port
    networks:
      - preprod-webfluxblog-network-overlay
    volumes:
      - preprod-webfluxblog-blog-service-local-volume:/uploads
      - /root/logs:/usr/app/logs
    environment:
      spring.profiles.active: preprod


networks:
  preprod-webfluxblog-network-overlay:
    external: true

volumes:
  preprod-webfluxblog-blog-service-local-volume:
    name: preprod-webfluxblog-blog-service-local-volume

# To build, docker-compose up --build -d or generally ./gradlew bootJar && docker-compose up --build -d